version: '3.8'

services:
  # Backend Flask
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sage_x3_backend
    ports:
      - "5000:5000"
    volumes:
      # Volumes persistants pour les données
      - sage_uploads:/app/uploads
      - sage_processed:/app/processed
      - sage_final:/app/final
      - sage_archive:/app/archive
      - sage_logs:/app/logs
      - sage_database:/app/database
      - sage_data:/app/data
    env_file:
      - ./.env
    environment:
      - FLASK_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Frontend React
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: sage_x3_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sage_uploads:
  sage_processed:
  sage_final:
  sage_archive:
  sage_logs:
  sage_database:
  sage_data: